[getJSON]
dir = ":cacheDir/:project"
maxAge = "10s"

[getCSV]
dir = ":cacheDir/:project"
maxAge = "10s"

[images]
dir = ":resourceDir/_gen"
maxAge = -1

[assets]
dir = ":resourceDir/_gen"
maxAge = -1

[modules]
dir = ":cacheDir/modules"
maxAge = -1
